### PR TITLE
Gradle cleanup and a breaking dependency update

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update .gitignore and delete two unneeded files

### 2nd commit
- Update gradle wrapper to 6.3 using git bash

### 3rd commit
- Misc space cleanup
- Update Kotlin 1.3.61 -> 1.3.71
- Update Android Studio 3.5.3 -> 3.6.2
- Update UnMock 0.7.4 -> 0.7.5
- Use jdk8 for Kotlin
- Update Mockito 2.9.0 -> 3.2.4 (it's not used, so that's easy)
- Update junit 4.12 -> 4.13

### 4th commit
- Update permissionsdispatcher 2.3.2 -> 4.7.0 ([changelog](https://github.com/permissions-dispatcher/PermissionsDispatcher/releases)), [migration guide](https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/doc/migration_guide.md) used
Read over the changelog and see if there's anything new you'd like to implement. (e.g. I think [this](https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/665) is perfect for this project.)

### CODE REVIEW

**Comment by TacoTheDank** [comment]
Did you accidentally hit request changes? I don't see anything to review.

**Comment by ligi** [comment]
strange - could swear I added a comment. It was about not wanting the change of having  google() on top

**Comment by TacoTheDank** [comment]
Fixed.

**Comment by ligi** [comment]
Thanks for the PR!

**Pull request merged**
